dbConfig:               # 数据库 配置 信息
  username: "root"  # "itg_srv"
  password: "20050901@mysqlHrx"
  hostname: "127.0.0.1"
  port: 3306
  dbname: "itg_doc"
  charset: "utf8mb4"
  parseTime: True
  local: "Local"
  
mailConfig:
  host: "smtp.163.com"
  port: 465
  from: "Haroxa@163.com"
  fromName: "集成文档"
  username: "Haroxa@163.com"
  password: "OAOVJUWLKBCAEULZ"